Debug = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = True
APP_PORT = 5001
APP_HOST = "127.0.0.1"
WX_APP_ID = ""
WX_APP_SECRET = ""
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://lbsign:lbsign@127.0.0.1:3306/lbsign"
